workflows:
  ios_release:
    name: Build iOS Release
    max_build_duration: 120
    instance_type: mac_mini
    env:
      FLUTTER_CHANNEL: stable
    setup:
      # تحديد النسخة الصحيحة من Flutter SDK
      flutter:
        channel: stable
    scripts:
      # تثبيت التبعيات إذا لزم الأمر
      - name: Install dependencies
        script: |
          flutter pub get
    ios:
      # لا حاجة للتوقيع في هذه الحالة
      export_method: app-store # أو adhoc حسب الحاجة
      build_mode: release
      codesign: false
    artifacts:
      - build/ios/ipa/*.ipa
    publish:
      # يمكنك نشر الـ IPA إلى Codemagic Artifacts إذا كنت بحاجة
      artifacts:
        - build/ios/ipa/*.ipa
